# Generated by Django 4.0.4 on 2022-05-02 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aperitivo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='creation',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
